open System.IO
open _2024

printfn "Day  1 Part 1: %i" (Day01Part1.run (File.ReadAllLines("../input/Day01/input.txt")))
printfn "Day  1 Part 2: %i" (Day01Part2.run (File.ReadAllLines("../input/Day01/input.txt")))
printfn "Day  2 Part 1: %i" (Day02Part1.run (File.ReadAllLines("../input/Day02/input.txt")))
printfn "Day  2 Part 2: %i" (Day02Part2.run (File.ReadAllLines("../input/Day02/input.txt")))
printfn "Day  3 Part 1: %i" (Day03Part1.run (File.ReadAllLines("../input/Day03/input.txt")))
//printfn "Day  3 Part 2: %i" (Day03Part2.run (File.ReadAllLines("../input/Day03/input1.txt")))
printfn "Day  4 Part 1: %i" (Day04Part1.run (File.ReadAllLines("../input/Day04/input.txt")))
printfn "Day  4 Part 2: %i" (Day04Part2.run (File.ReadAllLines("../input/Day04/input.txt")))
printfn "Day  5 Part 1: %i" (Day05Part1.run (File.ReadAllLines("../input/Day05/input.txt")))
printfn "Day  7 Part 1: %i" (Day07Part1.run (File.ReadAllLines("../input/Day07/input.txt")))
// printfn "Day  7 Part 2: %i" (Day07Part2.run (File.ReadAllLines("../input/Day07/input.txt")))
printfn "Day  9 Part 1: %i" (Day09Part1.run (File.ReadAllLines("../input/Day09/input.txt")[0]))
printfn "Day  9 Part 2: %i" (Day09Part2.run (File.ReadAllLines("../input/Day09/input.txt")[0]))
printfn "Day 11 Part 1: %i" (Day11Part1.run (File.ReadAllLines("../input/Day11/input.txt")[0]))
printfn "Day 11 Part 2: %i" (Day11Part2.run (File.ReadAllLines("../input/Day11/input.txt")[0]))
printfn "Day 14 Part 1: %i" (Day14Part1.run (File.ReadAllLines("../input/Day14/input.txt")))
printfn "Day 14 Part 2: %i" (Day14Part2.run (File.ReadAllLines("../input/Day14/input.txt")))