open System.IO
open _2025

printfn "Day  1 Part 1: %i" (Day01Part1.run (File.ReadAllLines("../input/Day01/input.txt")))
printfn "Day  1 Part 2: %i" (Day01Part2.run (File.ReadAllLines("../input/Day01/input.txt")))
printfn "Day  2 Part 1: %i" (Day02Part1.run (File.ReadAllLines("../input/Day02/input.txt")).[0])
printfn "Day  2 Part 2: %i" (Day02Part2.run (File.ReadAllLines("../input/Day02/input.txt")).[0])
printfn "Day  3 Part 1: %i" (Day03Part1.run (File.ReadAllLines("../input/Day03/input.txt")))
printfn "Day  3 Part 2: %i" (Day03Part2.run (File.ReadAllLines("../input/Day03/input.txt")))
printfn "Day  4 Part 1: %i" (Day04Part1.run (File.ReadAllLines("../input/Day04/input.txt")))
printfn "Day  4 Part 2: %i" (Day04Part2.run (File.ReadAllLines("../input/Day04/input.txt")))
printfn "Day  5 Part 1: %i" (Day05Part1.run (File.ReadAllLines("../input/Day05/input.txt")))
printfn "Day  5 Part 2: %i" (Day05Part2.run (File.ReadAllLines("../input/Day05/input.txt")))
printfn "Day  6 Part 1: %i" (Day06Part1.run (File.ReadAllLines("../input/Day06/input.txt")))
printfn "Day  6 Part 2: %i" (Day06Part2.run (File.ReadAllLines("../input/Day06/input.txt")))
printfn "Day  7 Part 1: %i" (Day07Part1.run (File.ReadAllLines("../input/Day07/input.txt")))
printfn "Day  7 Part 2: %i" (Day07Part2.run (File.ReadAllLines("../input/Day07/input.txt")))
printfn "Day  8 Part 1: %i" (Day08Part1.run (File.ReadAllLines("../input/Day08/input.txt")))
// printfn "Day  8 Part 2: %i" (Day08Part2.run (File.ReadAllLines("../input/Day08/input.txt"))) // Takes about 30 mins to run
printfn "Day  9 Part 1: %i" (Day09Part1.run (File.ReadAllLines("../input/Day09/input.txt")))
printfn "Day 10 Part 1: %i" (Day10Part1.run (File.ReadAllLines("../input/Day10/input.txt")))
printfn "Day 10 Part 2: %i" (Day10Part2.run (File.ReadAllLines("../input/Day10/input.txt")))
printfn "Day 11 Part 1: %i" (Day11Part1.run (File.ReadAllLines("../input/Day11/input.txt")))
printfn "Day 11 Part 2: %i" (Day11Part2.run (File.ReadAllLines("../input/Day11/input.txt")))
printfn "Day 12 Part 1: %i" (Day12Part1.run (File.ReadAllLines("../input/Day12/input.txt")))