open System.IO
open _2023

printfn "Day  1 Part 1: %i" (Day01Part1.calibrate (File.ReadAllLines("../input/Day01/input.txt")))
printfn "Day  1 Part 2: %i" (Day01Part2.calibrate (File.ReadAllLines("../input/Day01/input.txt")))
printfn "Day  2 Part 1: %i" (Day02Part1.gameSum (File.ReadAllLines("../input/Day02/input.txt")))
printfn "Day  2 Part 2: %i" (Day02Part2.cubePowers (File.ReadAllLines("../input/Day02/input.txt")))
printfn "Day  3 Part 1: %i" (Day03Part1.getSum (File.ReadAllLines("../input/Day03/input.txt")))
printfn "Day  3 Part 1: %i" (Day03Part2.getSum (File.ReadAllLines("../input/Day03/input.txt")))
printfn "Day  4 Part 1: %i" (Day04Part1.getSum (File.ReadAllLines("../input/Day04/input.txt")))
printfn "Day  4 Part 2: %i" (Day04Part2.getSum (File.ReadAllLines("../input/Day04/input.txt")))
printfn "Day  7 Part 1: %i" (Day07Part1.rankHands (File.ReadAllLines("../input/Day07/input.txt")))
printfn "Day  7 Part 2: %i" (Day07Part2.rankHands (File.ReadAllLines("../input/Day07/input.txt")))
printfn "Day  8 Part 1: %i" (Day08Part1.countSteps (File.ReadAllLines("../input/Day08/input.txt")))
printfn "Day  8 Part 2: %i" (Day08Part2.countSteps (File.ReadAllLines("../input/Day08/input.txt")))
printfn "Day  9 Part 1: %i" (Day09Part1.getSum (File.ReadAllLines("../input/Day09/input.txt")))
printfn "Day  9 Part 2: %i" (Day09Part2.getSum (File.ReadAllLines("../input/Day09/input.txt")))
// printfn "Day 10 Part 1: %A" (Day10Part1.getPipeLength (File.ReadAllLines("../input/Day10/input.txt")))
// printfn "Day 10 Part 2: %A" (Day10Part2.getArea (File.ReadAllLines("../input/Day10/input.txt")))
// printfn "Day 11 Part 1: %A" (Day11Part1.getSum (File.ReadAllLines("../input/Day11/input.txt")))
// printfn "Day 11 Part 2: %A" (Day11Part2.getSum (File.ReadAllLines("../input/Day11/input.txt")))
printfn "Day 13 Part 1: %i" (Day13Part1.getSum (File.ReadAllLines("../input/Day13/input.txt")))
printfn "Day 13 Part 2: %i" (Day13Part2.getSum (File.ReadAllLines("../input/Day13/input.txt")))
printfn "Day 14 Part 1: %i" (Day14Part1.getSum (File.ReadAllLines("../input/Day14/input.txt")))
printfn "Day 15 Part 1: %i" (Day15Part1.getSum (File.ReadAllLines("../input/Day15/input.txt")[0]))
printfn "Day 15 Part 2: %i" (Day15Part2.getSum (File.ReadAllLines("../input/Day15/input.txt")[0]))
// printfn "Day 16 Part 1: %A" (Day16Part1.countTiles (File.ReadAllLines("../input/Day16/input.txt")))
// printfn "Day 16 Part 2: %A" (Day16Part2.countTiles (File.ReadAllLines("../input/Day16/input.txt")))
printfn "Day 18 Part 1: %i" (Day18Part1.getArea (File.ReadAllLines("../input/Day18/input.txt")))
printfn "Day 18 Part 2: %i" (Day18Part2.getArea (File.ReadAllLines("../input/Day18/input.txt")))
printfn "Day 19 Part 1: %i" (Day19Part1.count (File.ReadAllLines("../input/Day19/parts.txt")))
printfn "Day 21 Part 1: %i" (Day21Part1.count (File.ReadAllLines("../input/Day21/input.txt")))
printfn "Day 24 Part 1: %i" (Day24Part1.getSum (File.ReadAllLines("../input/Day24/input.txt")))
printfn "Day 25 Part 1: %i" (Day25Part1.getResult (File.ReadAllLines("../input/Day25/input.txt")))
